"""Kafka topic name constants."""

REVIEW_CREATED = "review.created"
REVIEW_UPDATED = "review.updated"
REVIEW_DELETED = "review.deleted"
RESTAURANT_CREATED = "restaurant.created"
RESTAURANT_UPDATED = "restaurant.updated"
RESTAURANT_CLAIMED = "restaurant.claimed"
USER_CREATED = "user.created"
USER_UPDATED = "user.updated"
BOOKING_STATUS = "booking.status"
