apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-service
  namespace: yelp-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: review-service
  template:
    metadata:
      labels:
        app: review-service
    spec:
      containers:
        - name: review-service
          image: 904183418399.dkr.ecr.us-east-1.amazonaws.com/lab1-review-service:v1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8004
          env:
            - name: MONGODB_URL
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: MONGODB_URL
            - name: DB_NAME
              value: yelp_discovery
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: KAFKA_BOOTSTRAP_SERVERS
            - name: CORS_ORIGINS
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: CORS_ORIGINS
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: SECRET_KEY
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8004
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 256Mi
              cpu: 250m
