apiVersion: v1
kind: Service
metadata:
  name: review-service
  namespace: yelp-app
spec:
  type: ClusterIP
  selector:
    app: review-service
  ports:
    - port: 8004
      targetPort: 8004
      protocol: TCP
