apiVersion: v1
kind: Service
metadata:
  name: restaurant-owner-service
  namespace: yelp-app
spec:
  type: ClusterIP
  selector:
    app: restaurant-owner-service
  ports:
    - port: 8002
      targetPort: 8002
      protocol: TCP
